config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :books, only: :show

  get '/', to: 'home#index', as: :home
  get '/loader', to: 'home#loader'
  get '/not_found', to: 'home#not_found'

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :book_authors
  has_many :books, through: :book_authors

  validates :first_name, :last_name, presence: true

  def full_name
    "#{first_name} #{middle_name} #{last_name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :book_cover

  belongs_to :publisher

  has_many :book_authors
  has_many :authors, through: :book_authors

  validates :title, :price, :publish_at, :publisher, presence: true
  validates :isbn_number_10, presence: true, uniqueness: true
  validates :isbn_number_13, presence: true, uniqueness: true
  validate :at_least_one_author

  def self.search_by_isbn(isbn_number)
    isbn_10 = find_by(isbn_number_10: isbn_number)

    return isbn_10 if isbn_10.present?

    find_by(isbn_number_13: isbn_number)
  end

  private

  def at_least_one_author
    if authors.empty?
      errors.add(:base, "need at least one authors")
    end
  end
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_one :books

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: :show

  def show; end

  private

  def set_book
    @book = Book.search_by_isbn(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @books = Book.limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def format_isbn_number(number)
    number.insert(3, '-').insert(5, '-')
      .insert(12, '-').insert(15, '-')
  end
end

app/views/books/partials/_book_details.html.erb
<div class="mx-20">
  <div class="flex flex-col">
    <h1 class="text-4xl font-bold text-gray-700">Search Results: </h1>

    <div class="flex flex-col gap-10 md:flex-row">
      <div class="mt-10">
        <%= image_tag(book.book_cover, class: "h-auto max-w-sm rounded-lg") %>
      </div>

      <div class="flex flex-col gap-4 mt-6">
        <h1 class="text-3xl font-bold text-gray-900 mt-6 mb-4 text-left"><%= book.title %> </h1>

        <div class="text-lg font-semibold flex"> 
          by <%= book.authors.map(&:full_name).to_sentence %>
        </div>

        <div class="text-lg font-semibold flex mt-16"> 
          Edition: <p class="text-[#6362f2] ml-2"><%= book.edition %></p>
        </div>

        <div class="text-lg font-semibold flex"> 
          Price: <p class="text-[#6362f2] ml-2"> PHP <%= book.price.round(2) %> </p>
        </div>

        <div class="text-lg font-semibold flex"> 
          ISBN: <p class="text-[#6362f2] ml-2"> <%= format_isbn_number(book.isbn_number_13) %> </p>
        </div>

        <div class="text-lg font-semibold flex"> 
          Publication Year: <p class="text-[#6362f2] ml-2"> <%= book.publish_at.year %> </p>
        </div>

        <div class="text-lg font-semibold flex"> 
          Publisher: <p class="text-[#6362f2] ml-2"> <%= book.publisher.name %> </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/show.turbo_stream.erb
<%= turbo_stream.replace('page_content') do %>
  <%= turbo_frame_tag 'page_content' do %>
    <section class="flex flex-col py-24">
      <% if @book.blank? %>
        <%= render partial: 'shared/error_message', locals: { message: "ISBN not found" } %>
      <% else %>
        <%= render partial: 'books/partials/book_details', locals: { book: @book } %>
      <% end %>
    </section>
  <% end %>
<% end %>

app/views/home/error.turbo_stream.erb
<%= turbo_stream.replace('page_content') do %>
  <%= turbo_frame_tag 'page_content' do %>
    <section class="flex flex-col py-36">
      <%= render partial: 'shared/error_message', locals: { message: params[:message] } %>
    </section>
  <% end %>
<% end %>

app/views/home/index.html.erb
<%= turbo_frame_tag 'page_content' do %>
  <div class="flex flex-col">
    <%= render partial: 'home/partials/section_introduction' %>
    <%= render partial: 'home/partials/section_explore_books', locals: { books: @books } %>
    <%= render partial: 'home/partials/section_reviews' %>
    <%= render partial: 'home/partials/section_faq' %>
  </div>
<% end %>

app/views/home/index.turbo_stream.erb
<%= turbo_stream.replace 'page_content' do %>
  <%= turbo_frame_tag 'page_content' do %>
    <div class="flex flex-col">
      <%= render partial: 'home/partials/section_introduction' %>
      <%= render partial: 'home/partials/section_explore_books', locals: { books: @books } %>
      <%= render partial: 'home/partials/section_reviews' %>
      <%= render partial: 'home/partials/section_faq' %>
    </div>
  <% end %>
<% end %>

app/views/home/loader.turbo_stream.erb
<%= turbo_stream.replace('page_content') do %>
  <%= turbo_frame_tag 'page_content' do %>
    <section class="flex flex-col py-36">
      <%= render partial: 'shared/loader' %>
    </section>
  <% end %>
<% end %>

app/views/home/not_found.turbo_stream.erb
<%= turbo_stream.replace('page_content') do %>
  <%= turbo_frame_tag 'page_content' do %>
    <section class="flex flex-col py-36">
      <%= render partial: 'shared/error_message', locals: { message: params[:message] } %>
    </section>
  <% end %>
<% end %>

app/views/home/partials/_section_explore_books.html.erb
<section class="text-center flex flex-col pt-20">
  <div class="text-indigo-900 items-center mb-10">
    <h1 class="font-bold text-5xl">Explore Our Books</h1>

    <div class="font-medium text-lg text-center w-[50%] mx-auto my-10">
      With our dedicated customer support team, you can rest easy knowing that we're doing everything we can to save you time, money, and stress.
    </div>
  </div>

  <div class="flex flex-col mx-auto justify-center lg:flex-row">

    <% books.each do |book| %>
      <div class="flex flex-col tracking-wider mx-4 items-center">
        <%= image_tag(book.book_cover, class:"h-3/4 max-w-sm border-8 border-gray-300 rounded-lg") %>

        <div class="mx-auto">
          <div class="book-title text-3xl font-bold text-indigo-900 lg:text-gray-50 mt-6 mb-4 text-left ">
            <%= book.title %>
          </div>

          <div class="text-left font-medium text-cyan-500 text-lg">
            <%= link_to book_path(id: book.isbn_number_13), data: { turbo_stream: true } do %>
              View Book Details <i class="fa-solid fa-chevron-right"></i>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="relative w-full h-auto z-[-1] pb-16">
    <div class="h-auto w-full bg-[#061935] absolute bottom-0 top-[-15rem] -skew-y-3 z-[-1]"></div>

    <div class="flex flex-col tracking-wider mx-28 mt-20">
      <div class="text-gray-50 mb-10 text-left">
        <h1 class="font-bold text-4xl">3 Reason To Shop With Us</h1>
      </div>

      <div class="flex flex-col mt-10 lg:flex-row">
        <div class="text-gray-50 pr-16 my-5">
          <div class="mb-10">
            <img src="/box.svg" />
          </div>

          <div class="text-left">
            <h1 class="text-2xl font-semibold mb-6 pr-20">All textbook rentals come with free return shipping.</h1>
            <p class="text-base font-normal text-gray-200">Lorem ipsum keme keme keme 48 years bella na biway at nang chuckie 
              dites sa ng shala ugmas at bakit , conalei quality control doonek at nang effem ang kirara sa.</p>
          </div>
        </div>

        <div class="text-gray-50 pr-16 my-5">
          <div class="mb-10">
            <img src="/help.svg" />
          </div>

          <div class="text-left">
            <h1 class="text-2xl font-semibold mb-6 pr-20">Dedicated customer support and help portal.</h1>
            <p class="text-base font-normal text-gray-200">Lorem ipsum keme keme keme 48 years bella na biway at nang chuckie 
              dites sa ng shala ugmas at bakit , conalei quality control doonek at nang effem ang kirara sa.</p>
          </div>
        </div>

        <div class="text-gray-50 pr-16 my-5">
          <div class="mb-10">
            <img src="/baboy.svg" />
          </div>

          <div class="text-left">
            <h1 class="text-2xl font-semibold mb-6">Buy or rent cheap textbooks & save up to $500 per year!</h1>
            <p class="text-base font-normal text-gray-200">Lorem ipsum keme keme keme 48 years bella na biway at nang chuckie 
              dites sa ng shala ugmas at bakit , conalei quality control doonek at nang effem ang kirara sa.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/partials/_section_faq.html.erb
<section class="flex flex-col bg-[#eceef1] py-36">
  <div class="mx-auto">
    <h1 class="font-bold text-4xl text-[#141c55] mb-10 px-10">Frequently Asked Question</h1>

    <div class="flex flex-col">
      <%= render partial: 'shared/accordion', locals: { title: 'Dedicated customer support and help portal.', icon_position: 'up' } %>
      <%= render partial: 'shared/accordion', locals: { title: 'Lorem ipsum keme keme keme 48 years at bakit mahogany ang Mike', icon_position: 'up' } %>
      <%= render partial: 'shared/accordion', locals: { title: 'Lorem ipsum keme keme keme 48 years at bakit mahogany ang Mike', icon_position: 'up' } %>
      <%= render partial: 'shared/accordion', locals: { title: 'Lorem ipsum keme keme keme 48 years at bakit mahogany ang Mike', icon_position: 'up' } %>
    </div>
  </div>
</section>

app/views/home/partials/_section_introduction.html.erb
<section class="bg-banner bg-cover bg-no-repeat w-full h-full pb-20">
  <div class="flex flex-col">
    <div class="flex flex-col mx-auto lg:flex-row my-8"> 
      <div class="pl-20 flex flex-col justify-center max-w-screen-sm lg:px-10">
        <div class="text-5xl w-[60%] font-bold mb-8">
          <h1><%= t('sections.introduction.title') %></h1>
        </div>
        <div class="text-2xl w-[60%] font-semibold text-[#4b64ff]">
          <h3><%= t('sections.introduction.subtitle') %> </h3>
        </div>
        <div class="w-[80%] my-8">
          Lorem ipsum keme keme keme 48 years quality control mahogany shongaers kasi antibiotic klapeypey-klapeypey 
          na ang pamin na ng keme at nang bakit shogal sa lorem ipsum keme keme ganda lang shokot guash jowa bella 
        </div>

        <div class="flex justify-between">
          <button class="text-white bg-[#4b64ff] hover:bg-[#2c3fb2] focus:ring-4 focus:ring-blue-300 font-normal rounded-xl text-base px-8 py-4 shadow-[#697dfc] shadow-lg"> 
            Get Started 
            <i class="fa-solid fa-chevron-right ml-2 text-gray-50 fa-sm"></i> 
          </button>
        </div>
      </div>

      <div class="my-8">
        <img src="/hero.svg" class="object-fit"/>
      </div>
    </div>

    <div class="flex flex-col-reverse mx-auto lg:flex-row my-8 space-x-20"> 
      <div class="mt-20 content-center lg:my-8">
        <img src="/group.png" class="ml-20 object-fit"/>
      </div>

      <div class="flex flex-col justify-center max-w-screen-sm">
        <div class="text-5xl w-[70%] text-gray-50 font-bold mb-8">
          <h1><%= t('sections.commitment.title') %></h1>
        </div>
        <div class="w-[80%] mb-8 text-gray-50">
          Lorem ipsum keme keme keme 48 years quality control mahogany shongaers kasi antibiotic klapeypey-klapeypey 
          na ang pamin na ng keme at nang bakit shogal sa lorem ipsum keme keme ganda lang shokot guash jowa bella 
        </div>

        <div class="flex justify-between">
          <button class="text-cyan-400 bg-cyan-950 hover:bg-cyan-800 focus:ring-4 focus:ring-blue-300 font-normal rounded-xl text-base px-8 py-4 shadow-[#697dfc] shadow-lg"> 
            Learn More
            <i class="fa-solid fa-chevron-right ml-2 text-cyan-400 fa-sm"></i> 
          </button>
        </div>
      </div>
    </div>

    <div class="text-5xl text-center font-bold py-10 flex flex-col">
      <h1 class="text-gray-50">Trusted By Awesome <span class="text-amber-400">Clients</span></h1>

      <div class="mx-auto flex flex-col justify-between lg:flex-row">
        <div class="binance flex items-center my-16 mx-10">
          <svg id="Group_13703" data-name="Group 13703" xmlns="http://www.w3.org/2000/svg" width="52.723" height="52.723" viewBox="0 0 52.723 52.724">
            <path id="Path_9173" data-name="Path 9173" d="M30.369,22.154l10.24-10.236L50.853,22.162,56.808,16.2,40.609,0,24.41,16.2Z" transform="translate(-14.243)" fill="#ffffff"/>
            <path id="Path_9174" data-name="Path 9174" d="M0,0H8.424V8.424H0Z" transform="translate(0 26.363) rotate(-45)" fill="#ffffff"/>
            <path id="Path_9175" data-name="Path 9175" d="M30.357,73.4,40.6,83.644,50.842,73.4,56.8,79.351l0,0-16.2,16.2L24.4,79.363l-.008-.008Z" transform="translate(-14.231 -42.834)" fill="#ffffff"/>
            <path id="Path_9176" data-name="Path 9176" d="M0,0H8.424V8.424H0Z" transform="translate(40.809 26.364) rotate(-45)" fill="#ffffff"/>
            <path id="Path_9177" data-name="Path 9177" d="M60.873,54.827,54.831,48.78l-4.468,4.468-.516.512-1.058,1.058-.008.008.008.012,6.042,6.038,6.042-6.047,0,0Z" transform="translate(-28.465 -28.467)" fill="#ffffff"/>
          </svg>
          <p class="text-white text-2xl font-medium ml-2">Binance</p>
        </div>

        <div class="binance flex items-center my-16 mx-10">
          <svg id="Layer_x0020_1" xmlns="http://www.w3.org/2000/svg" width="52.701" height="52.707" viewBox="0 0 52.701 52.707">
            <g id="_1421344023328" transform="translate(0 0)">
              <path id="Path_9185" data-name="Path 9185" d="M51.912,32.729A26.344,26.344,0,1,1,32.722.789a26.346,26.346,0,0,1,19.19,31.94h0Z" transform="translate(0 -0.001)" fill="#fff"/>
              <path id="Path_9186" data-name="Path 9186" d="M1020.618,726.168c.525-3.507-2.146-5.392-5.8-6.65l1.184-4.751-2.892-.72-1.153,4.626c-.76-.19-1.541-.368-2.317-.546l1.161-4.656-2.89-.721-1.185,4.749c-.629-.143-1.247-.285-1.847-.434l0-.015-3.988-1-.769,3.089s2.146.492,2.1.522a1.539,1.539,0,0,1,1.348,1.682l-1.349,5.412a2.33,2.33,0,0,1,.3.1l-.306-.076-1.891,7.581a1.052,1.052,0,0,1-1.325.687c.029.042-2.1-.525-2.1-.525l-1.436,3.31,3.763.938c.7.176,1.386.359,2.062.532l-1.2,4.805,2.889.721,1.185-4.754c.789.214,1.555.412,2.3.6l-1.181,4.732,2.892.72,1.2-4.8c4.931.933,8.639.557,10.2-3.9,1.258-3.591-.063-5.662-2.657-7.013a4.611,4.611,0,0,0,3.692-4.246h0Zm-6.607,9.265c-.894,3.591-6.94,1.65-8.9,1.163l1.588-6.366C1008.659,730.719,1014.945,731.687,1014.011,735.433Zm.894-9.317c-.815,3.266-5.848,1.607-7.48,1.2l1.44-5.774c1.632.407,6.89,1.166,6.041,4.574Z" transform="translate(-982.647 -703.569)" fill="#5fd2fa"/>
            </g>
          </svg>
          <p class="text-white text-2xl font-medium ml-2">Bitcoin</p>
        </div>

        <div class="binance flex items-center my-16 mx-10">
          <svg id="solana-sol-logo" xmlns="http://www.w3.org/2000/svg" width="52.317" height="41" viewBox="0 0 52.317 41">
            <path id="Path_9193" data-name="Path 9193" d="M8.48,234.6a1.712,1.712,0,0,1,1.21-.5H51.44a.855.855,0,0,1,.605,1.46L43.8,243.807a1.712,1.712,0,0,1-1.21.5H.837a.855.855,0,0,1-.605-1.46Z" transform="translate(0.02 -203.307)" fill="#fff"/>
            <path id="Path_9194" data-name="Path 9194" d="M8.48.5A1.759,1.759,0,0,1,9.69,0H51.44a.855.855,0,0,1,.605,1.46L43.8,9.707a1.712,1.712,0,0,1-1.21.5H.837a.855.855,0,0,1-.605-1.46Z" transform="translate(0.02)" fill="#fff"/>
            <path id="Path_9195" data-name="Path 9195" d="M43.8,116.8a1.712,1.712,0,0,0-1.21-.5H.837a.855.855,0,0,0-.605,1.46l8.247,8.247a1.712,1.712,0,0,0,1.21.5H51.44a.855.855,0,0,0,.605-1.46Z" transform="translate(0.02 -101.002)" fill="#fff"/>
          </svg>

          <p class="text-white text-2xl font-medium ml-2">Solana</p>
        </div>

        <div class="binance flex items-center my-16 mx-10">
          <svg id="Layer_x0020_1" xmlns="http://www.w3.org/2000/svg" width="32.604" height="53.097" viewBox="0 0 32.604 53.097">
            <g id="_1421394342400">
              <g id="Group_13698" data-name="Group 13698">
                <path id="Path_9187" data-name="Path 9187" d="M383.856,0,383.5,1.21V36.319l.356.355,16.3-9.633Z" transform="translate(-367.559)" fill="#5fd2fa"/>
                <path id="Path_9188" data-name="Path 9188" d="M16.3,0,0,27.041l16.3,9.633V0Z" fill="#e3f8ff"/>
                <path id="Path_9189" data-name="Path 9189" d="M387.441,734.518l-.2.245v12.506l.2.586,16.307-22.965Z" transform="translate(-371.144 -694.759)" fill="#5fd2fa"/>
                <path id="Path_9190" data-name="Path 9190" d="M16.3,747.855V734.518L0,724.89Z" transform="translate(0 -694.759)" fill="#e3f8ff"/>
                <path id="Path_9191" data-name="Path 9191" d="M392.07,489.371l16.3-9.633-16.3-7.408Z" transform="translate(-375.773 -452.697)" fill="#4fbde3"/>
                <path id="Path_9192" data-name="Path 9192" d="M0,479.738l16.3,9.633V472.33Z" transform="translate(0 -452.697)" fill="#5fd2fa"/>
              </g>
            </g>
          </svg>

          <p class="text-white text-2xl font-medium ml-2">Etherium</p>
        </div>

        <div class="binance flex items-center my-16 mx-10">
          <svg id="tether-usdt-logo" xmlns="http://www.w3.org/2000/svg" width="59.775" height="52" viewBox="0 0 59.775 52">
            <path id="Path_9196" data-name="Path 9196" d="M10.95.255.05,23.15a.444.444,0,0,0,.1.518L29.582,51.875a.449.449,0,0,0,.622,0L59.641,23.669a.444.444,0,0,0,.1-.518L48.836.257a.44.44,0,0,0-.4-.257H11.355a.44.44,0,0,0-.405.255Z" transform="translate(-0.005 0)" fill="#fff" fill-rule="evenodd"/>
            <path id="Path_9197" data-name="Path 9197" d="M86.49,58.646h0c-.211.016-1.3.081-3.739.081-1.937,0-3.313-.058-3.8-.081h0c-7.486-.329-13.074-1.633-13.074-3.193s5.588-2.862,13.074-3.2v5.091c.49.035,1.891.118,3.829.118,2.325,0,3.489-.1,3.7-.116V52.26c7.471.333,13.046,1.636,13.046,3.193s-5.574,2.86-13.046,3.191h0Zm0-6.912V47.178H96.916V40.23H68.53v6.948H78.954v4.554C70.482,52.121,64.11,53.8,64.11,55.81s6.372,3.688,14.844,4.079v14.6h7.534v-14.6c8.453-.389,14.814-2.066,14.814-4.075s-6.356-3.686-14.814-4.077h0Zm0,0Z" transform="translate(-52.821 -33.145)" fill="#5fd2fa" fill-rule="evenodd"/>
          </svg>

          <p class="text-white text-2xl font-medium ml-2">Tether</p>
        </div>

        <div class="binance flex items-center my-16 mx-10">
          <svg id="Layer_2" data-name="Layer 2" xmlns="http://www.w3.org/2000/svg" width="50.745" height="42.023" viewBox="0 0 50.745 42.023">
            <g id="Layer_1" data-name="Layer 1">
              <path id="Path_9198" data-name="Path 9198" d="M44.158,0h7.334L36.23,15.112a14.264,14.264,0,0,1-20.02,0L.94,0H8.28l11.6,11.48a9.03,9.03,0,0,0,12.677,0Z" transform="translate(-0.847)" fill="#5fd2fa"/>
              <path id="Path_9199" data-name="Path 9199" d="M7.339,248.5H0L15.362,233.29a14.264,14.264,0,0,1,20.02,0L50.745,248.5H43.411l-11.7-11.573a9.03,9.03,0,0,0-12.677,0Z" transform="translate(0 -206.472)" fill="#e3f8ff"/>
            </g>
          </svg>

          <p class="text-white text-2xl font-medium ml-2">XRP</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XyzBooks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: 'shared/header' %>

    <main>
      <%= yield %>
    </main>

    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/shared/_accordion.html.erb
<div class="w-full block">
  <button type="button" class="text-[#6161f2] py-5 font-medium flex justify-between rtl:text-right w-full items-center gap-x-72 px-10">
    <span class="text-lg"><%= title %></span>
    <i class="fa-solid fa-chevron-<%= icon_position %>"></i>
  </button>

  <%= turbo_frame_tag 'accordion_body' %>
</div>

app/views/shared/_error_message.html.erb
<div class="mx-auto text-center">
  <div class="flex">
    <h1 class="text-4xl font-bold text-gray-700">Search Results: </h1>
    <h1 class="text-4xl font-bold text-red-700 ml-4"><%= message %></h1>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="h-[7vh] bg-promo bg-contain"></div>

<nav class="bg-[#fcfcfc] border-gray-200 h-auto w-auto mt-2 tracking-wide"  data-controller="search">
  <div class="max-w-screen-3xl flex flex-wrap items-center justify-between mx-10 p-4">
    <div class="col-span-1 text-right">
      <img src="/xyz-logo.svg" class="h-full" />
    </div>

      <div class="flex xl:order-1 text-center justify-end xl:justify-normal"> 
        <div class="relative hidden xl:block">
          <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <i class="fa-solid fa-magnifying-glass text-gray-500"></i>
            <span class="sr-only">Search icon</span>
          </div>

          <input type="text" class="block w-[150%] p-2 ps-10 text-sm text-gray-900 border border-[#5465e7] rounded-full bg-gray-50 focus:ring-blue-500 focus:border-blue-500" placeholder="Search" data-action="keydown.enter->search#searchBookNumber">
        </div>

        <button type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-gray-500 rounded-lg xl:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200" data-action="click->search#toggleSearchNav">
            <i class="fa-solid fa-bars fa-xl"></i>
        </button>
      </div>

      <div class="items-center justify-between hidden w-full rounded-xl xl:flex xl:w-auto xl:order-1 bg-gray-50 xl:bg-transparent p-4 xl:shadow-none xl:p-0 shadow-xl" data-search-target="searchNav">
        <div class="relative mt-3 xl:hidden">
          <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
            <i class="fa-solid fa-magnifying-glass"></i>
          </div>
          <input type="text" class="block w-full p-2 ps-10 text-sm text-gray-900 border border-[#5465e7] rounded-full bg-gray-50 focus:ring-blue-500 focus:border-blue-500" placeholder="Search" data-action="keydown.enter->search#searchBookNumber">
        </div>
        
        <ul class="flex flex-col p-4 xl:p-0 mt-4 mr-4 font-medium rounded-lg xl:space-x-8 rtl:space-x-reverse xl:flex-row xl:mt-0 xl:border-0">
          <li>
            <%= link_to 'Home', home_path, class: 'header-nav-actions' %>
          </li>
          <li>
            <a href="/" class="header-nav-actions">Rent Textbooks</a>
          </li>
          <li>
            <a href="/" class="header-nav-actions">Buy Textbooks</a>
          </li>
          <li>
            <a href="/" class="header-nav-actions">Sell Textbooks</a>
          </li>
        </ul>

        <div class="h-5 border border-gray-300 hidden xl:flex"></div>
  
        <div class="items-center flex ml-5">
          <a href="#" class="block py-2 px-5 text-gray-900 rounded hover:bg-gray-100 xl:hover:bg-transparent xl:hover:text-blue-700 xl:p-0">
            <i class="fa-solid fa-globe text-[#5fd2fa] fa-lg"></i> En
          </a>

          <button class="text-white bg-[#4b64ff] hover:bg-[#2c3fb2] focus:ring-4 focus:ring-blue-300 font-medium rounded-xl text-sm px-6 py-4 ml-5 shadow-[#697dfc] shadow-lg"> Contact </button>
        </div>
      </div>
  </div>
</nav>

app/views/shared/_loader.html.erb
<div class="mx-auto text-center">
    <i class="fa-solid fa-spinner fa-5x animate-spin text-gray-400"></i>
</div>

app/views/shared/accoridion_partials/_accordion_body.html.erb
<div class="p-5 border border-b-0 border-gray-200">
  <p class="mb-2 text-gray-500">Flowbite is an open-source library of interactive components built on top of Tailwind CSS including buttons, dropdowns, modals, navbars, and more.</p>
</div>